export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  publishDate: string;
  readTime: string;
  featuredImage: string;
  category: string;
  keywords: string[];
  games?: string[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: "best-arcades-in-houston",
    title: "Best Arcades in Houston TX (2026) | 6 Arcades Ranked & Compared",
    description: "Ranked: best arcades in Houston. Cidercade, Game Preserve, Dave & Buster's, Zero Latency VR. Prices from $12–$50. Full comparison with pros, cons, and who each venue suits best.",
    publishDate: "2026-03-20",
    readTime: "12 min",
    featuredImage: "/hero_img.webp",
    category: "Guides",
    keywords: ["best houston arcade", "best arcade houston", "arcades in houston"],
  },
  {
    slug: "cidercade-houston-review",
    title: "Cidercade Houston Review | 275+ Games, $12 All-Day, Bar & Pizza",
    description: "Cidercade Houston review: 275+ free-play games, $12 all-day admission, hand-crafted pizza, craft beer bar, East Downtown location. Is it worth it?",
    publishDate: "2026-03-18",
    readTime: "7 min",
    featuredImage: "/outbreak-group-fun.webp",
    category: "Reviews",
    keywords: ["cidercade houston", "cidercade review", "best houston arcade"],
  },
  {
    slug: "game-preserve-houston-review",
    title: "Game Preserve Houston Review | Retro Arcade, Pinball, Free Play",
    description: "Game Preserve Houston review: 100+ retro games, pinball machines, $15 day pass, Woodlands and NASA Webster locations. Best retro arcade in Houston?",
    publishDate: "2026-03-16",
    readTime: "6 min",
    featuredImage: "/post-game-group.jpg",
    category: "Reviews",
    keywords: ["game preserve houston", "retro arcade houston", "pinball houston"],
  },
  {
    slug: "retro-arcade-houston",
    title: "Retro Arcade Houston | Classic Games, Pinball & Vintage Cabinets (2026)",
    description: "Houston's retro arcade scene: Game Preserve (100+ classics), Cidercade retro section. Where to find pinball machines, Street Fighter cabinets, and vintage gaming in Houston TX.",
    publishDate: "2026-03-14",
    readTime: "8 min",
    featuredImage: "/arena-action.jpg",
    category: "Guides",
    keywords: ["retro arcade houston", "vintage arcade houston", "classic arcade houston", "pinball houston"],
  },
  {
    slug: "arcade-bar-houston",
    title: "Arcade Bar Houston | Best 18+ Arcades with Drinks (2026)",
    description: "Houston's top arcade bars: Cidercade (hard cider + 275 games, 18+ at 9pm), Dave & Buster's (cocktails + sports). Compare drink menus, atmospheres, and age policies.",
    publishDate: "2026-03-12",
    readTime: "7 min",
    featuredImage: "/pvp-experience.webp",
    category: "Guides",
    keywords: ["arcade bar houston", "arcade houston bar", "adult arcade bar", "18+ arcade houston"],
  },
  {
    slug: "arcades-in-houston-for-kids",
    title: "Arcades in Houston for Kids | Family-Friendly Guide (2026)",
    description: "Kid-friendly arcades in Houston: Game Preserve (family-oriented, all ages), Cidercade (daytime family-friendly), Zero Latency VR (Engineerium ages 6+). Pricing and tips for each.",
    publishDate: "2026-03-10",
    readTime: "9 min",
    featuredImage: "/Family-Adventure.webp",
    category: "Guides",
    keywords: ["arcade houston for kids", "arcade in houston for kids", "family arcade houston", "kid friendly houston"],
  },
  {
    slug: "arcades-in-houston-for-adults",
    title: "Arcades in Houston for Adults | 18+, Bar Arcades & VR (2026)",
    description: "Adult arcades in Houston: Cidercade 18+ after 9pm with full bar, Dave & Buster's cocktails and sports, Zero Latency VR for groups and date nights. Full comparison.",
    publishDate: "2026-03-08",
    readTime: "8 min",
    featuredImage: "/pvp.webp",
    category: "Guides",
    keywords: ["arcade houston for adults", "arcade in houston for adults", "houston nightlife", "adult arcade houston"],
  },
  {
    slug: "free-play-arcades-houston",
    title: "Free Play Arcades Houston | Unlimited Games from $12 (2026)",
    description: "Free-play arcades in Houston: Cidercade ($12 all-day, 275+ games) vs Game Preserve ($15 day pass, 100+ retro games). No tokens, no quarters — just press start.",
    publishDate: "2026-03-06",
    readTime: "6 min",
    featuredImage: "/experience.webp",
    category: "Guides",
    keywords: ["free play arcade houston", "unlimited play admission", "free arcade houston", "cidercade houston"],
  },
  {
    slug: "houston-arcade-birthday-party-guide",
    title: "Arcade Birthday Party Houston | All Venues Compared (2026 Guide)",
    description: "Houston arcade birthday party guide: Cidercade party zones, Game Preserve private room ($250), Dave & Buster's packages, Zero Latency VR private arena. Pricing and what's included.",
    publishDate: "2026-03-04",
    readTime: "10 min",
    featuredImage: "/venue-birthday-party.webp",
    category: "Events",
    keywords: ["arcade birthday party", "birthday parties houston", "arcade party houston"],
  },
  {
    slug: "bachelor-bachelorette-party-houston",
    title: "Bachelor & Bachelorette Party Houston | VR Arcade, Bar & Activities",
    description: "Best bachelor and bachelorette party ideas in Houston: Zero Latency VR adrenaline experience, Cidercade arcade bar, Dave & Buster's dinner and games. Group booking tips.",
    publishDate: "2026-03-02",
    readTime: "7 min",
    featuredImage: "/venue-bachelor-party.webp",
    category: "Events",
    keywords: ["bachelor party houston", "bachelorette party houston", "group activities houston"],
  },
  {
    slug: "vr-arcade-houston",
    title: "VR Arcade Houston | Free-Roam Virtual Reality at Arcade Houston",
    description: "Complete guide to VR arcade experiences in Houston. Zero Latency Webster, Houston's 8 free-roam multiplayer games explained: pricing, what to expect, how it compares to other options.",
    publishDate: "2026-02-28",
    readTime: "10 min",
    featuredImage: "/venue-arena.webp",
    category: "Guides",
    keywords: ["vr arcade houston", "free roam vr houston", "virtual reality houston"],
  },
  {
    slug: "best-vr-games-houston-zero-latency",
    title: "Best VR Games in Houston | All 8 Games at Arcade Houston Ranked",
    description: "All 8 Zero Latency VR games ranked and compared. Player counts, durations, intensity levels, and which game is best for your group — families, adults, competitive players.",
    publishDate: "2026-02-26",
    readTime: "9 min",
    featuredImage: "/experiences-hero.webp",
    category: "Guides",
    keywords: ["best vr games houston", "zero latency houston games", "vr arcade houston"],
  },
  {
    slug: "zero-latency-houston-complete-guide",
    title: "Zero Latency Webster, Houston Guide | VR Arcade at ArcadeHouston.com",
    description: "Complete Zero Latency Webster, Houston guide: location, pricing, all 8 VR games, what to expect, booking tips, and 5.0-star review summary. Everything you need before your visit.",
    publishDate: "2026-02-24",
    readTime: "8 min",
    featuredImage: "/Webster_Houston.webp",
    category: "Guides",
    keywords: ["zero latency houston", "vr arcade houston", "arcade houston"],
  },
  {
    slug: "things-to-do-houston-texas-this-weekend",
    title: "Things to Do in Houston This Weekend | Arcades, VR, Entertainment (2026)",
    description: "Weekend activities in Houston: 6 arcade venues, VR gaming, bar arcades, family entertainment. Includes pricing, locations, and what each venue does best.",
    publishDate: "2026-02-22",
    readTime: "10 min",
    featuredImage: "/outbreak-group-fun.webp",
    category: "Houston",
    keywords: ["things to do in houston", "houston fun activities", "arcade houston", "entertainment houston"],
  },
  {
    slug: "things-to-do-clear-lake-houston",
    title: "Things to Do in Clear Lake Houston | Arcades, VR & Entertainment",
    description: "Clear Lake Houston activities: Zero Latency VR and Game Preserve NASA are both in nearby Webster. Plus dining, outdoor activities, and NASA Space Center.",
    publishDate: "2026-02-20",
    readTime: "8 min",
    featuredImage: "/Webster_Houston.webp",
    category: "Houston",
    keywords: ["things to do clear lake houston", "clear lake houston", "arcade houston near me"],
  },
  {
    slug: "things-to-do-webster-tx",
    title: "Things to Do in Webster TX | Arcades, VR, Great Wolf Lodge",
    description: "Webster TX activities: Zero Latency VR, Game Preserve NASA, and Great Wolf Lodge Northern Lights Arcade — all in one area. Complete guide to Webster entertainment.",
    publishDate: "2026-02-18",
    readTime: "7 min",
    featuredImage: "/venue-lounge-area.webp",
    category: "Houston",
    keywords: ["things to do webster tx", "webster tx", "arcade houston near me"],
  },
  {
    slug: "birthday-party-ideas-houston",
    title: "Birthday Party Ideas Houston | Arcade Parties, VR & More (2026)",
    description: "Houston birthday party ideas: arcade parties at Cidercade, Game Preserve, Dave & Buster's, and Zero Latency VR. Pricing, capacity, and what each includes.",
    publishDate: "2026-02-16",
    readTime: "9 min",
    featuredImage: "/party.webp",
    category: "Events",
    keywords: ["birthday party ideas houston", "birthday parties houston", "arcade birthday party"],
  },
  {
    slug: "team-building-activities-houston",
    title: "Team Building Activities Houston | VR Arcade, Games & Events",
    description: "Houston corporate team building: Zero Latency VR co-op missions and PvP tournaments, Dave & Buster's private rooms, Cidercade group outings. Pricing and booking guide.",
    publishDate: "2026-02-14",
    readTime: "8 min",
    featuredImage: "/venue-team-building.webp",
    category: "Events",
    keywords: ["team building activities houston", "corporate events houston", "group activities houston"],
  },
  {
    slug: "date-night-ideas-houston",
    title: "Date Night Ideas Houston | Arcade Bar, VR, Games (2026)",
    description: "Houston date night: Cidercade arcade bar (18+, pizza, craft beer), Zero Latency VR (adrenaline date), Dave & Buster's Date Night Duo. Best options by budget and vibe.",
    publishDate: "2026-02-12",
    readTime: "7 min",
    featuredImage: "/pvp-experience.webp",
    category: "Houston",
    keywords: ["arcade date houston", "date night ideas houston", "houston date night", "arcade bar houston"],
  },
  {
    slug: "group-activities-houston-tx",
    title: "Group Activities Houston TX | Arcades, VR & Party Venues",
    description: "Group activities in Houston: arcade parties, VR team games, bar arcade outings. All venues compared by group size, pricing, and what makes each one worth booking.",
    publishDate: "2026-02-10",
    readTime: "8 min",
    featuredImage: "/post-game-group.jpg",
    category: "Events",
    keywords: ["group activities houston", "houston entertainment venues", "arcade houston"],
  },
];

export function getAllBlogPosts(): BlogPost[] {
  return blogPosts;
}

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}
